### ISSUE TITLE
Protocol Basics: Registration tokens

### ISSUE THREAD

**Issue by jmking-iftas** [mastodon/fediverse_auxiliary_service_provider_specifications#18]
Currently:

> Registration tokens are JSON Web Tokens (JWT) as defined in [RFC-7519](https://datatracker.ietf.org/doc/html/rfc7519).

Should it be

> Registration tokens MUST be JSON Web Tokens (JWT) as defined in [RFC-7519](https://datatracker.ietf.org/doc/html/rfc7519).

**Comment by oneiros** [comment]
No longer relevant due to #27
