### ISSUE TITLE
Provider specifications: OAuth 2.0 Scopes: "aux" prefix

### ISSUE THREAD

**Issue by jmking-iftas** [mastodon/fediverse_auxiliary_service_provider_specifications#19]
Currently the spec requires fediverse server side scopes to be prefaced with `aux`, but I wonder if `fasp` makes it clearer from the server side admin point of view?

aux:debug becomes fasp:debug
aux:account_search:write becomes fasp:account_search:write

This helps clearly reinforce the intent of the scope, references the spec, and helps reduce possible confusion with languages such as French where "aux" is a word in normal usage that may infer different meaning out of context,

**Comment by oneiros** [comment]
We did not have the acronym "fasp" when I wrote that and I thought "aux" was in the name and at least likely to not collide with anything you would usually find.

But now that you coined that acronym I agree. Good idea!

**Comment by oneiros** [comment]
No longer relevant due to #27
